# "prettier options": "https://prettier.io/docs/en/options.html"

singleQuote: true
trailingComma: all
proseWrap: never
endOfLine: lf
quoteProps: consistent
jsxSingleQuote: true
semi: false
useTabs: false
xmlWhitespaceSensitivity: 'ignore'
plugins:
  # ref: https://github.com/tailwindlabs/prettier-plugin-tailwindcss
  # Error with addDynamicIconSelectors getLocalIconSets
  - 'prettier-plugin-tailwindcss'
